---
# Include variables and define needed variables.
- name: Check if apache_vhosts is defined
  ansible.builtin.assert:
    that:
      - apache_vhosts is defined
    fail_msg: "The variable apache_vhosts has to be defined in (group|host)_vars."

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages
  ansible.builtin.set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when:
    - "apache_packages is not defined"
    - "ansible_os_family == 'RedHat'"
    - "ansible_distribution_major_version == '9'"

- name: Define apache_packages
  ansible.builtin.set_fact:
    apache_packages: "{{ ['elinks'] + __apache_packages }}"
  when:
    - "apache_packages is not defined"
    - "ansible_os_family == 'RedHat'"
    - "ansible_distribution_major_version != '9'"

- name: Copying the files
  ansible.builtin.include_tasks: "copy_Files.yml"
  when: apache_vhosts is defined

- name: Setup and install tasks
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Configure httpd
  ansible.builtin.include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Ensure Apache has selected state and enabled on boot
  ansible.builtin.systemd:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: yes

# Setup logrotate
- name: Setup logrotate for httpd
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/httpd
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: Disable welcome.conf
  ansible.builtin.copy:
    content: ""
    dest: /etc/httpd/conf.d/welcome.conf
    mode: '0644'

- name: Flush handlers at role end
  ansible.builtin.include_tasks: flush_handlers.yml
